//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Adoptante
{
    public partial class Dashboard
    {
        /// <summary>
        /// litNombreUsuario control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNombreUsuario;

        /// <summary>
        /// litFavoritos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFavoritos;

        /// <summary>
        /// litSolicitudes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSolicitudes;

        /// <summary>
        /// pnlMascotas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMascotas;

        /// <summary>
        /// rptMascotas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptMascotas;

        /// <summary>
        /// pnlSinMascotas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSinMascotas;
    }
}
