//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Adoptante
{
    public partial class Favoritos
    {
        protected global::System.Web.UI.WebControls.Literal litConteo;
        protected global::System.Web.UI.WebControls.Panel pnlFavoritos;
        protected global::System.Web.UI.WebControls.Repeater rptFavoritos;
        protected global::System.Web.UI.WebControls.Panel pnlVacio;
    }
}
