//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Adoptante
{
    public partial class Mascotas
    {
        /// <summary>
        /// txtBuscar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>
        /// ddlEspecie control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEspecie;

        /// <summary>
        /// ddlEdad control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEdad;

        /// <summary>
        /// ddlTamano control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTamano;

        /// <summary>
        /// btnFiltrar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnFiltrar;

        /// <summary>
        /// btnLimpiar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLimpiar;

        /// <summary>
        /// litConteo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litConteo;

        /// <summary>
        /// pnlMascotas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMascotas;

        /// <summary>
        /// rptMascotas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptMascotas;

        /// <summary>
        /// pnlVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlVacio;
    }
}
