//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Adoptante
{
    public partial class MisReportes
    {
        protected global::System.Web.UI.WebControls.Literal litMisPerdidas;
        protected global::System.Web.UI.WebControls.Literal litMisEncontradas;
        protected global::System.Web.UI.WebControls.Literal litAvistamientos;
        protected global::System.Web.UI.WebControls.Literal litReunidas;
        protected global::System.Web.UI.WebControls.Panel pnlReportes;
        protected global::System.Web.UI.WebControls.Repeater rptReportes;
        protected global::System.Web.UI.WebControls.Panel pnlSinReportes;
    }
}
