//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Adoptante
{
    public partial class PerfilMascota
    {
        /// <summary>
        /// litTitulo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTitulo;

        /// <summary>
        /// pnlNoEncontrado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoEncontrado;

        /// <summary>
        /// pnlMascota control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMascota;

        /// <summary>
        /// litEstado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEstado;

        /// <summary>
        /// litEmoji control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmoji;

        /// <summary>
        /// btnFavorito control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnFavorito;

        /// <summary>
        /// litThumb1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litThumb1;

        /// <summary>
        /// litNombre control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNombre;

        /// <summary>
        /// litRaza control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRaza;

        /// <summary>
        /// litTagEspecie control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTagEspecie;

        /// <summary>
        /// litTagEdad control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTagEdad;

        /// <summary>
        /// litTagTamano control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTagTamano;

        /// <summary>
        /// litTagSexo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTagSexo;

        /// <summary>
        /// litTagUbicacion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTagUbicacion;

        /// <summary>
        /// litNombre2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNombre2;

        /// <summary>
        /// litDescripcion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDescripcion;

        /// <summary>
        /// pnlVacunado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlVacunado;

        /// <summary>
        /// pnlEsterilizado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEsterilizado;

        /// <summary>
        /// pnlDesparasitado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlDesparasitado;

        /// <summary>
        /// pnlTemperamento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTemperamento;

        /// <summary>
        /// litTemperamento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTemperamento;

        /// <summary>
        /// litRefugioInicial control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRefugioInicial;

        /// <summary>
        /// litRefugioNombre control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRefugioNombre;

        /// <summary>
        /// litRefugioCiudad control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRefugioCiudad;

        /// <summary>
        /// btnAdoptar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnAdoptar;
    }
}
