//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Adoptante
{
    public partial class PerfilMascota
    {
        /// <summary>
        /// litTitulo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTitulo;

        /// <summary>
        /// litNombreBreadcrumb control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNombreBreadcrumb;

        /// <summary>
        /// pnlMascota control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMascota;

        /// <summary>
        /// imgMascota control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgMascota;

        /// <summary>
        /// litEmojiGrande control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmojiGrande;

        /// <summary>
        /// btnFavorito control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnFavorito;

        /// <summary>
        /// litNombre control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNombre;

        /// <summary>
        /// pnlNuevo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNuevo;

        /// <summary>
        /// litEstado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEstado;

        /// <summary>
        /// litUbicacion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUbicacion;

        /// <summary>
        /// litEspecie control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEspecie;

        /// <summary>
        /// litRaza control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRaza;

        /// <summary>
        /// litEdad control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEdad;

        /// <summary>
        /// litEdadDetalle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEdadDetalle;

        /// <summary>
        /// litSexo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSexo;

        /// <summary>
        /// litTamano control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTamano;

        /// <summary>
        /// litColor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litColor;

        /// <summary>
        /// pnlTemperamento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTemperamento;

        /// <summary>
        /// litTemperamento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTemperamento;

        /// <summary>
        /// pnlDescripcion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlDescripcion;

        /// <summary>
        /// litDescripcion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDescripcion;

        /// <summary>
        /// litRefugioInicial control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRefugioInicial;

        /// <summary>
        /// litRefugioNombre control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRefugioNombre;

        /// <summary>
        /// litRefugioCiudad control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRefugioCiudad;

        /// <summary>
        /// iconVacunado control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl iconVacunado;

        /// <summary>
        /// iconEsterilizado control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl iconEsterilizado;

        /// <summary>
        /// iconDesparasitado control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl iconDesparasitado;

        /// <summary>
        /// pnlNecesidades control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNecesidades;

        /// <summary>
        /// litNecesidades control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNecesidades;

        /// <summary>
        /// pnlNoEncontrado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoEncontrado;

        /// <summary>
        /// pnlCTA control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlCTA;

        /// <summary>
        /// btnAdoptar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnAdoptar;

        /// <summary>
        /// litNombreModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNombreModal;

        /// <summary>
        /// rptFotos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptFotos;

        /// <summary>
        /// pnlSinFotos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSinFotos;

        /// <summary>
        /// litEmojiModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmojiModal;
    }
}
