//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Adoptante
{
    public partial class ReportarMascota
    {
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.RadioButton rbPerdida;
        protected global::System.Web.UI.WebControls.RadioButton rbEncontrada;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.DropDownList ddlEspecie;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEspecie;
        protected global::System.Web.UI.WebControls.TextBox txtRaza;
        protected global::System.Web.UI.WebControls.TextBox txtColor;
        protected global::System.Web.UI.WebControls.DropDownList ddlTamano;
        protected global::System.Web.UI.WebControls.DropDownList ddlSexo;
        protected global::System.Web.UI.WebControls.DropDownList ddlEdad;
        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDescripcion;
        protected global::System.Web.UI.WebControls.TextBox txtUbicacion;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUbicacion;
        protected global::System.Web.UI.WebControls.TextBox txtCiudad;
        protected global::System.Web.UI.WebControls.HiddenField hfLatitud;
        protected global::System.Web.UI.WebControls.HiddenField hfLongitud;
        protected global::System.Web.UI.WebControls.TextBox txtFecha;
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTelefono;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.Button btnEnviar;
    }
}
