//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Adoptante
{
    public partial class SolicitudAdopcion
    {
        /// <summary>
        /// pnlPerfilIncompleto control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPerfilIncompleto;

        /// <summary>
        /// pnlSolicitudExistente control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSolicitudExistente;

        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>
        /// litError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litError;

        /// <summary>
        /// pnlFormulario control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;

        /// <summary>
        /// imgMascota control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgMascota;

        /// <summary>
        /// pnlEmoji control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmoji;

        /// <summary>
        /// litEmoji control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmoji;

        /// <summary>
        /// litNombreMascota control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNombreMascota;

        /// <summary>
        /// litEspecie control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEspecie;

        /// <summary>
        /// litUbicacion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUbicacion;

        /// <summary>
        /// litEdad control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEdad;

        /// <summary>
        /// litNombreBreadcrumb control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNombreBreadcrumb;

        /// <summary>
        /// txtMotivo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotivo;

        /// <summary>
        /// rfvMotivo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMotivo;

        /// <summary>
        /// txtExperiencia control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtExperiencia;

        /// <summary>
        /// rbCasa control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButton rbCasa;

        /// <summary>
        /// rbApartamento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButton rbApartamento;

        /// <summary>
        /// rbFinca control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButton rbFinca;

        /// <summary>
        /// chkPatioJardin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkPatioJardin;

        /// <summary>
        /// chkOtrasMascotas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkOtrasMascotas;

        /// <summary>
        /// pnlOtrasMascotas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlOtrasMascotas;

        /// <summary>
        /// txtOtrasMascotas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtOtrasMascotas;

        /// <summary>
        /// chkNinos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkNinos;

        /// <summary>
        /// pnlNinos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNinos;

        /// <summary>
        /// txtEdadesNinos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEdadesNinos;

        /// <summary>
        /// ddlHorasEnCasa control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlHorasEnCasa;

        /// <summary>
        /// rfvHoras control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvHoras;

        /// <summary>
        /// ddlIngresos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlIngresos;

        /// <summary>
        /// chkAceptaVisita control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkAceptaVisita;

        /// <summary>
        /// txtComentarios control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtComentarios;

        /// <summary>
        /// btnEnviar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnEnviar;

        /// <summary>
        /// fuFoto1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuFoto1;

        /// <summary>
        /// fuFoto2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuFoto2;

        /// <summary>
        /// fuFoto3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuFoto3;
    }
}
