//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Admin
{
    public partial class Auditoria
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlAccion;
        protected global::System.Web.UI.WebControls.DropDownList ddlTabla;
        protected global::System.Web.UI.WebControls.TextBox txtFechaDesde;
        protected global::System.Web.UI.WebControls.TextBox txtFechaHasta;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Repeater rptAuditoria;
        protected global::System.Web.UI.WebControls.Panel pnlSinRegistros;
    }
}
