//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Admin
{
    public partial class Configuracion
    {
        protected global::System.Web.UI.WebControls.LinkButton tabCriterios;
        protected global::System.Web.UI.WebControls.LinkButton tabEspecies;
        protected global::System.Web.UI.WebControls.LinkButton tabSeguridad;

        // Panel Criterios
        protected global::System.Web.UI.WebControls.Panel pnlCriterios;
        protected global::System.Web.UI.WebControls.HiddenField hdnCriterioId;
        protected global::System.Web.UI.WebControls.TextBox txtCriterioNombre;
        protected global::System.Web.UI.WebControls.TextBox txtCriterioPeso;
        protected global::System.Web.UI.WebControls.TextBox txtCriterioPuntaje;
        protected global::System.Web.UI.WebControls.TextBox txtCriterioDescripcion;
        protected global::System.Web.UI.WebControls.Button btnGuardarCriterio;
        protected global::System.Web.UI.WebControls.Button btnCancelarCriterio;
        protected global::System.Web.UI.WebControls.Repeater rptCriterios;

        // Panel Especies
        protected global::System.Web.UI.WebControls.Panel pnlEspecies;
        protected global::System.Web.UI.WebControls.HiddenField hdnEspecieId;
        protected global::System.Web.UI.WebControls.TextBox txtEspecieNombre;
        protected global::System.Web.UI.WebControls.Button btnGuardarEspecie;
        protected global::System.Web.UI.WebControls.Repeater rptEspecies;
        protected global::System.Web.UI.WebControls.HiddenField hdnRazaId;
        protected global::System.Web.UI.WebControls.DropDownList ddlEspecieRaza;
        protected global::System.Web.UI.WebControls.TextBox txtRazaNombre;
        protected global::System.Web.UI.WebControls.Button btnGuardarRaza;
        protected global::System.Web.UI.WebControls.Repeater rptRazas;

        // Panel Seguridad
        protected global::System.Web.UI.WebControls.Panel pnlSeguridad;
        protected global::System.Web.UI.WebControls.TextBox txtIntentosMaximos;
        protected global::System.Web.UI.WebControls.TextBox txtExpiracionToken;
        protected global::System.Web.UI.WebControls.TextBox txtLongitudPassword;
        protected global::System.Web.UI.WebControls.Button btnGuardarSeguridad;
        protected global::System.Web.UI.WebControls.Label lblMensajeSeguridad;
    }
}
