//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Admin
{
    public partial class MascotasPerdidas
    {
        protected global::System.Web.UI.WebControls.Literal litTotalReportes;
        protected global::System.Web.UI.WebControls.Literal litPerdidas;
        protected global::System.Web.UI.WebControls.Literal litEncontradas;
        protected global::System.Web.UI.WebControls.Literal litReunidas;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipo;
        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;
        protected global::System.Web.UI.WebControls.TextBox txtBusqueda;
        protected global::System.Web.UI.WebControls.Button btnBuscar;
        protected global::System.Web.UI.WebControls.Repeater rptReportes;
        protected global::System.Web.UI.WebControls.Panel pnlSinReportes;
    }
}
