//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Admin
{
    public partial class Notificaciones
    {
        protected global::System.Web.UI.WebControls.Button btnNuevaNotificacion;
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;
        protected global::System.Web.UI.WebControls.DropDownList ddlDestinatarios;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipo;
        protected global::System.Web.UI.WebControls.TextBox txtTitulo;
        protected global::System.Web.UI.WebControls.TextBox txtMensaje;
        protected global::System.Web.UI.WebControls.Button btnEnviar;
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Repeater rptNotificaciones;
        protected global::System.Web.UI.WebControls.Panel pnlSinNotificaciones;
    }
}
