//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Admin
{
    public partial class Refugios
    {
        /// <summary>
        /// Control litTotalRefugios.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalRefugios;

        /// <summary>
        /// Control litVerificados.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litVerificados;

        /// <summary>
        /// Control litPendientes.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPendientes;

        /// <summary>
        /// Control ddlFiltroVerificado.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltroVerificado;

        /// <summary>
        /// Control txtBusqueda.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBusqueda;

        /// <summary>
        /// Control btnBuscar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>
        /// Control rptRefugios.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRefugios;

        /// <summary>
        /// Control pnlSinResultados.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSinResultados;
    }
}
