//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Admin
{
    public partial class Reportes
    {
        /// <summary>
        /// Control litTotalUsuarios.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalUsuarios;

        /// <summary>
        /// Control litTotalRefugios.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalRefugios;

        /// <summary>
        /// Control litTotalMascotas.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalMascotas;

        /// <summary>
        /// Control litTotalAdopciones.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalAdopciones;

        /// <summary>
        /// Control litReportesTotales.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litReportesTotales;

        /// <summary>
        /// Control litReportesPerdidas.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litReportesPerdidas;

        /// <summary>
        /// Control litReportesEncontradas.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litReportesEncontradas;

        /// <summary>
        /// Control litReportesReunidas.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litReportesReunidas;

        /// <summary>
        /// Control litTotalAvistamientos.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotalAvistamientos;

        /// <summary>
        /// Control rptUsuariosPorRol.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptUsuariosPorRol;

        /// <summary>
        /// Control rptMascotasPorEstado.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptMascotasPorEstado;

        /// <summary>
        /// Control rptAdopcionesMensuales.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptAdopcionesMensuales;

        /// <summary>
        /// Control rptTopRefugios.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptTopRefugios;

        /// <summary>
        /// Control pnlSinRefugios.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSinRefugios;

        protected global::System.Web.UI.WebControls.Button btnExportarExcel;
    }
}
