//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Admin
{
    public partial class Usuarios
    {
        /// <summary>
        /// Control ddlFiltroRol.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltroRol;

        /// <summary>
        /// Control ddlFiltroEstado.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltroEstado;

        /// <summary>
        /// Control txtBusqueda.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBusqueda;

        /// <summary>
        /// Control btnBuscar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>
        /// Control rptUsuarios.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptUsuarios;

        /// <summary>
        /// Control pnlSinResultados.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSinResultados;

        /// <summary>
        /// Control pnlModalAsignar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlModalAsignar;

        /// <summary>
        /// Control hdnUsuarioId.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnUsuarioId;

        /// <summary>
        /// Control ddlRefugios.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRefugios;

        /// <summary>
        /// Control btnCancelarAsignar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelarAsignar;

        /// <summary>
        /// Control btnConfirmarAsignar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmarAsignar;

        /// <summary>
        /// Control pnlModalVerificar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlModalVerificar;

        /// <summary>
        /// Control hdnRefugioVerificarId.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnRefugioVerificarId;

        /// <summary>
        /// Control imgRefugioVerif.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgRefugioVerif;

        /// <summary>
        /// Control litNombreRefugioVerif.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNombreRefugioVerif;

        /// <summary>
        /// Control litCiudadRefugioVerif.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCiudadRefugioVerif;

        /// <summary>
        /// Control litDireccionRefugioVerif.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDireccionRefugioVerif;

        /// <summary>
        /// Control litTelefonoRefugioVerif.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTelefonoRefugioVerif;

        /// <summary>
        /// Control litDescripcionRefugioVerif.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDescripcionRefugioVerif;

        /// <summary>
        /// Control litMascotasRefugioVerif.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMascotasRefugioVerif;

        /// <summary>
        /// Control litFechaRefugioVerif.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFechaRefugioVerif;

        /// <summary>
        /// Control pnlEstadoVerificado.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEstadoVerificado;

        /// <summary>
        /// Control btnCerrarVerificar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCerrarVerificar;

        /// <summary>
        /// Control btnQuitarVerificacion.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnQuitarVerificacion;

        /// <summary>
        /// Control btnAprobarVerificacion.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAprobarVerificacion;

        /// <summary>
        /// Control lblMensaje.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMensaje;
    }
}
