//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Public
{
    public partial class DetalleReporte
    {
        protected global::System.Web.UI.WebControls.Literal litTitulo;
        protected global::System.Web.UI.WebControls.HiddenField hfReporteData;
        protected global::System.Web.UI.WebControls.Panel pnlReporte;
        protected global::System.Web.UI.WebControls.Panel pnlEstadoBadge;
        protected global::System.Web.UI.WebControls.Literal litEstado;
        protected global::System.Web.UI.WebControls.Image imgMascota;
        protected global::System.Web.UI.WebControls.Literal litNombre;
        protected global::System.Web.UI.WebControls.Literal litTipoReporte;
        protected global::System.Web.UI.WebControls.Literal litEspecie;
        protected global::System.Web.UI.WebControls.Literal litRaza;
        protected global::System.Web.UI.WebControls.Literal litColor;
        protected global::System.Web.UI.WebControls.Literal litTamano;
        protected global::System.Web.UI.WebControls.Literal litSexo;
        protected global::System.Web.UI.WebControls.Literal litDescripcion;
        protected global::System.Web.UI.WebControls.Panel pnlCaracteristicas;
        protected global::System.Web.UI.WebControls.Literal litCaracteristicas;
        protected global::System.Web.UI.WebControls.Literal litTelefono;
        protected global::System.Web.UI.WebControls.Literal litEmail;
        protected global::System.Web.UI.WebControls.Literal litUbicacion;
        protected global::System.Web.UI.WebControls.Panel pnlAccionesDueno;
        protected global::System.Web.UI.WebControls.Button btnMarcarReunido;
        protected global::System.Web.UI.WebControls.Literal litFechaReporte;
        protected global::System.Web.UI.WebControls.Literal litUbicacionReporte;
        protected global::System.Web.UI.WebControls.Repeater rptAvistamientos;
        protected global::System.Web.UI.WebControls.Panel pnlSinAvistamientos;
        protected global::System.Web.UI.WebControls.TextBox txtDescripcionAvi;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDescripcion;
        protected global::System.Web.UI.WebControls.TextBox txtUbicacionAvi;
        protected global::System.Web.UI.WebControls.HiddenField hfLatitud;
        protected global::System.Web.UI.WebControls.HiddenField hfLongitud;
        protected global::System.Web.UI.WebControls.FileUpload fuFotoAvi;
        protected global::System.Web.UI.WebControls.Button btnRegistrarAvistamiento;
        protected global::System.Web.UI.WebControls.Panel pnlNoEncontrado;
    }
}
