//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Public
{
    public partial class MapaExtravios
    {
        /// <summary>
        /// litPerdidas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPerdidas;

        /// <summary>
        /// litEncontradas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEncontradas;

        /// <summary>
        /// ddlFiltroTipo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltroTipo;

        /// <summary>
        /// hfReportesJson control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfReportesJson;
    }
}
