//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.Public
{
    public partial class RegistrarAvistamiento
    {
        protected global::System.Web.UI.WebControls.Panel pnlInfoReporte;
        protected global::System.Web.UI.WebControls.Literal litNombreReporte;
        protected global::System.Web.UI.WebControls.Literal litInfoReporte;
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.HiddenField hfIdReporte;
        protected global::System.Web.UI.WebControls.TextBox txtUbicacion;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUbicacion;
        protected global::System.Web.UI.WebControls.TextBox txtFechaAvistamiento;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFecha;
        protected global::System.Web.UI.WebControls.HiddenField hfLat;
        protected global::System.Web.UI.WebControls.HiddenField hfLng;
        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDescripcion;
        protected global::System.Web.UI.WebControls.Button btnEnviar;
    }
}
