//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.AdminRefugio
{
    public partial class Actividad
    {
        /// <summary>
        /// rptActividad control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptActividad;

        /// <summary>
        /// pnlNoData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoData;
    }
}
