//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.AdminRefugio
{
    public partial class Perfil
    {
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Image imgFotoActual;
        protected global::System.Web.UI.WebControls.FileUpload fuFotoPerfil;
        protected global::System.Web.UI.WebControls.TextBox txtNombreRefugio;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombreRefugio;
        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;
        protected global::System.Web.UI.WebControls.TextBox txtCiudad;
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;
        protected global::System.Web.UI.WebControls.HiddenField hfLatitud;
        protected global::System.Web.UI.WebControls.HiddenField hfLongitud;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtClaveActual;
        protected global::System.Web.UI.WebControls.TextBox txtNuevaClave;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmarClave;
        protected global::System.Web.UI.WebControls.Label lblErrorClave;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
