//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedPatitas.AdminRefugio
{
    public partial class RevisarSolicitud
    {
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlContenido;
        protected global::System.Web.UI.WebControls.Image imgMascota;
        protected global::System.Web.UI.WebControls.Panel pnlEmoji;
        protected global::System.Web.UI.WebControls.Literal litEmoji;
        protected global::System.Web.UI.WebControls.Literal litNombreMascota;
        protected global::System.Web.UI.WebControls.Literal litNombreAdoptante;
        protected global::System.Web.UI.WebControls.Literal litFechaSolicitud;
        protected global::System.Web.UI.WebControls.Literal litEstado;
        protected global::System.Web.UI.WebControls.Literal litAdoptanteNombre;
        protected global::System.Web.UI.WebControls.Literal litAdoptanteCedula;
        protected global::System.Web.UI.WebControls.Literal litAdoptanteTelefono;
        protected global::System.Web.UI.WebControls.Literal litAdoptanteEmail;
        protected global::System.Web.UI.WebControls.Literal litAdoptanteCiudad;
        protected global::System.Web.UI.WebControls.Literal litMotivacion;
        protected global::System.Web.UI.WebControls.Literal litExperiencia;
        protected global::System.Web.UI.WebControls.Literal litTipoVivienda;
        protected global::System.Web.UI.WebControls.Literal litPatioJardin;
        protected global::System.Web.UI.WebControls.Literal litHorasEnCasa;
        protected global::System.Web.UI.WebControls.Panel pnlFotos;
        protected global::System.Web.UI.WebControls.Repeater rptFotos;
        protected global::System.Web.UI.WebControls.Panel pnlSinFotos;
        protected global::System.Web.UI.WebControls.Literal litOtrasMascotas;
        protected global::System.Web.UI.WebControls.Literal litNinos;
        protected global::System.Web.UI.WebControls.Panel pnlDetallesOtrasMascotas;
        protected global::System.Web.UI.WebControls.Literal litDetalleOtrasMascotas;
        protected global::System.Web.UI.WebControls.Panel pnlEdadesNinos;
        protected global::System.Web.UI.WebControls.Literal litEdadesNinos;
        protected global::System.Web.UI.WebControls.Literal litIngresos;
        protected global::System.Web.UI.WebControls.Literal litAceptaVisita;
        protected global::System.Web.UI.WebControls.Panel pnlComentarios;
        protected global::System.Web.UI.WebControls.Literal litComentarios;
        protected global::System.Web.UI.WebControls.HiddenField hfIdSolicitud;
        protected global::System.Web.UI.WebControls.HiddenField hfPuntajeTotal;
        protected global::System.Web.UI.WebControls.HiddenField hfEvaluaciones;
        protected global::System.Web.UI.WebControls.HiddenField hfTipoVivienda;
        protected global::System.Web.UI.WebControls.HiddenField hfTienePatio;
        protected global::System.Web.UI.WebControls.HiddenField hfHorasEnCasa;
        protected global::System.Web.UI.WebControls.HiddenField hfIngresos;
        protected global::System.Web.UI.WebControls.HiddenField hfOtrasMascotas;
        protected global::System.Web.UI.WebControls.HiddenField hfTieneNinos;
        protected global::System.Web.UI.WebControls.HiddenField hfTextoMotivacion;
        protected global::System.Web.UI.WebControls.HiddenField hfTextoExperiencia;
        protected global::System.Web.UI.WebControls.Button btnAprobar;
        protected global::System.Web.UI.WebControls.Button btnRechazar;
        protected global::System.Web.UI.WebControls.Panel pnlModalRechazo;
        protected global::System.Web.UI.WebControls.TextBox txtMotivoRechazo;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMotivo;
        protected global::System.Web.UI.WebControls.Button btnCancelarRechazo;
        protected global::System.Web.UI.WebControls.Button btnConfirmarRechazo;
    }
}
